version: '3'

services:

  ### Gateway ###
  gateway-service:
    build:
      context: gateway
    ports:
      - "8080:8080"
      - "7001:5005"
    networks:
      - sally-gateway-network
  ######

  ### User Service ###
  user-service:
    build:
      context: user-service
    ports:
    - "7002:5005" # for debug
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - user-service-postgres
    networks:
      - sally-user-service-network
      - sally-gateway-network
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar ./user-service.jar

  user-service-postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: user-service-db
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: root
    networks:
      - sally-user-service-network
  ######

  ### Shop Service ###
  shop-service:
    build:
      context: shop-service
    ports:
    - "7003:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - shop-service-postgres
      - axon-server
    networks:
      - sally-gateway-network
      - sally-shop-service-network
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar ./shop-service.jar

  shop-service-postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: shop-service-db
      POSTGRES_USER: shop-service
      POSTGRES_PASSWORD: root
    networks:
      - sally-shop-service-network
  #######

  ### Product Search Service ###
  product-search-service:
    #restart: on-failure
    build:
      context: product-search-service
    ports:
      - "7004:5005"
    depends_on:
      - ps-elasticksearch
      - axon-server
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar ./product-search-service.jar
    networks:
      - sally-gateway-network
      - sally-product-search-service-network

  ps-elasticksearch:
    image: "elasticsearch:7.6.2"
    container_name: ps-elasticksearch
    mem_reservation: 2G
    environment:
      - "discovery.type=single-node"
    networks:
      - sally-product-search-service-network
  #######

  ### Order Service
  order-service:

  #################

  ### Axon Server ###
  axon-server:
    image: axoniq/axonserver
    networks:
      - sally-shop-service-network
      - sally-gateway-network
  ###################


networks:
  sally-gateway-network:
  sally-user-service-network:
  sally-shop-service-network:
  sally-product-search-service-network: