apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      serviceAccountName: cloud-sql-sa
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          readinessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: {{ .Values.service.readinessProbe }}
          livenessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: {{ .Values.service.livenessProbe }}
          env:
            - name: SALLY_SUPER_NAME
              value: {{ .Values.sally.superUserName }}
            - name: DATA_SOURCE_URL
              value: {{ .Values.datasource.url }}
            - name: DATA_SOURCE_USERNAME
              value: {{ .Values.datasource.username }}
            - name: JWT_TOKEN_VALIDITY
              value: {{ .Values.jwt.tokenValidity }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: -secrets
                  key: jwtToken
            - name: DATA_SOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: -secrets
                  key: datasourcePassword
            - name: SALLY_SUPER_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: -secrets
                  key: sallySuperUserPassword
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=vlad-proj-test:us-central1:sallydb=tcp:5432"
          securityContext:
           runAsNonRoot: true