apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.name }}-secrets
stringData:
  jwtToken: {{ .Values.jwt.secret }}
  sallySuperUserPassword: {{ .Values.sally.superUserPassword }}
  datasourcePassword: {{ .Values.datasource.password }}



