service:
  livenessProbe: /actuator/health/liveness
  readinessProbe: /actuator/health/readiness
container:
  name: sally-user
  port: 8080
  image: userImage # change during CD
  tag: userTag # change during CD
replicas: 1
sally:
  superUserName: Vlad
  superUserPassword: qweqwe # change during CD
datasource:
  url: jdbc:postgresql://127.0.0.1:5432/user-service-db
  username: postgres
  password: qweqwe # change during CD
jwt:
  tokenValidity: 6000
  secret: qweqwe # change during CD