service:
  livenessProbe: /actuator/health/liveness
  readinessProbe: /actuator/health/readiness
container:
  name: sally-gateway
  port: 8080
  image: gatewayImage # change during CD
  tag: gatewayTag # change during CD
replicas: 1
userServiceHost: http://sally-user-service
shopServiceHost: http://sally-shop-service
orderServiceHost: http://sally-order-service
productSearchServiceHost: http://sally-product-search-service