apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: {{ .Values.service.livenessProbe }}
          readinessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: {{ .Values.service.readinessProbe }}
          env:
            - name: USER_SERVICE_HOST
              value: {{ .Values.userServiceHost }}
            - name: SHOP_SERVICE_HOST
              value: {{ .Values.shopServiceHost }}
            - name: ORDER_SERVICE_HOST
              value: {{ .Values.orderServiceHost }}
            - name: PRODUCT_SEARCH_SERVICE_HOST
              value: {{ .Values.productSearchServiceHost }}
